host: dimos.med.uoa.gr
server:
  port: ${PORT:8443}
  ssl:
    key-store-type: JKS
    key-store: classpath:dimos.jks
    key-store-password: mgs1971
    key-alias: dimos.p12
  servlet:
    context-path: /dmms
spring:
  session:
    store-type: redis
  redis:
    host: redis-docker-server
    port: 6379
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true
zuul:
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: auth-server
    videolecture:
      path: /api/videolecture/**
      serviceId: videolecture-service
      sensitive-headers:
    institution:
      path: /api/institution/**
      serviceId: institution-service
      sensitive-headers:
    sa:
      path: /sa/**
      serviceId: admin-service
      sensitive-headers:
    user:
      path: /api/user/**
      sensitive-headers:
      serviceId: user-service
ribbon:
  eureka:
    enabled: true

eureka.client.registerWithEureka: false

odc:
  ldap:
      server: ldap-server
      port: 8389
      connection: ldap://${odc.ldap.server}:${odc.ldap.port}/dc=springframework,dc=org
      dn-Patterns: uid={0},ou=people
      group-search-base: ou=groups
      password-attribute: userPassword
  mongodb:
    url: mongodb-server
    port: 27017
    collection: i3Delos
  cas:
    service: https://${host}:${server.port}${server.servlet.context-path}/cas/login
    key: casAuthProviderKey
    server:
     saml11-ticker-validator: https://login.uoa.gr/
     filter-processes-url: /cas/login
     login-url: https://login.uoa.gr/login
     cas-server-url-prefix: https://login.uoa.gr/
