server:
  port: ${PORT:8443}
  ssl:
    key-store-type: JKS
    key-store: classpath:dimos.jks
    key-store-password: mgs1971
    key-alias: dimos.p12
  servlet:
    context-path: /dmms
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true
zuul:
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: auth-server
    videolecture:
      path: /api/videolecture/**
      serviceId: videolecture-service
      sensitive-headers:
    institution:
      path: /api/institution/**
      serviceId: institution-service
      sensitive-headers:
    sa:
      path: /sa/**
      serviceId: admin-service
      sensitive-headers:
    user:
      path: /api/user/**
      sensitive-headers:
      serviceId: user-service
ribbon:
  eureka:
    enabled: true
    
